### ISSUE TITLE
Upgrade depecrated HTTP Client

### ISSUE THREAD

**Issue by markuscodes1** [Crazy-Marvin/yogibot-website#82]
Currently, the project uses the `@angular/http` package to perform http requests which is deprecated since angular version 8. It should be replaced with `@angular/common/http`.

This change must be made before #81 can be processed

**Comment by NimperX** [comment]
May I work on this issue?

**Comment by markuscodes1** [comment]
There is already a pull request for it #83

**Comment by CrazyMarvin** [comment]
Thanks!
#83 is merged now. ☺️

**Comment by NimperX** [comment]
May i work on #81 then?

**Comment by CrazyMarvin** [comment]
I would like to give @markuscodes1 the choice to do it himself since he came first.
Markus, are you up for #81?

@NimperX, what are your skills? Maybe we can find something else for you.

**Comment by markuscodes1** [comment]
Yeah, I'm still working on it.

Maybe @NimperX  can refactor the services. Currently, the HTTP observables are converted to promises. It would be better when the RxJs operators are used

**Comment by CrazyMarvin** [comment]
That's a great plan, Markus. 😎

**Comment by NimperX** [comment]
Sure @markuscodes1.😋 I will work on refactoring.

**Comment by markuscodes1** [comment]
This issue can be closed
