### ISSUE TITLE
Refactor Services

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/yogibot-website#84]
I can assign you here, @NimperX. 😃

**Comment by NimperX** [comment]
Cool @CrazyMarvin. I'll go with this.

**Comment by markuscodes1** [comment]
Maybe add an better description and some tags to this issue

**Comment by CrazyMarvin** [comment]
@NimperX did some refactoring in #88. Do you think the issue can be closed then?

**Comment by markuscodes1** [comment]
I've comment my review on #88. This PR only refactors the `SayingService` and not the `YogiBotService `

**Comment by CrazyMarvin** [comment]
I cannot find your comment, @markuscodes1. 😅
Where do I have to look?

**Comment by markuscodes1** [comment]
Sorry forgot to submit the review. Take a look again into #88

**Comment by NimperX** [comment]
@CrazyMarvin I think this issue can be closed, cause all the changes metioned inthe issue had been resolved in last commit of #89 (commit b93db4df4d33a62ed64f0c5a5f15f2faf792cfd3 )
